
spring:
  # AZURE の設定
  cloud:
    azure:
      credential:
        client-id:      ${AZURE_CLIENT_ID}
        client-secret:  ${AZURE_CLIENT_SECRET}
      profile:
        tenant-id:      ${AZURE_TENANT_ID}
      active-directory:
        enabled:          true
        redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
        authorization-clients:
          graph:
            scopes:
            - email
            - openid
            - profile
